{{- range .Values.services }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  host: {{ .name }}
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
---
{{- end }} 