global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8080']
  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8081']
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8082']
  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8083']
  - job_name: 'loadbalancer'
    static_configs:
      - targets: ['loadbalancer:9000'] 