name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.24'
        
    - name: Build
      run: go build ./cmd/...
      env:
        CGO_ENABLED: 0
        
    - name: Test
      run: go test -v -race ./...
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        load: true
        tags: sme-platform:${{ github.sha }}
        
    - name: Security Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'sme-platform:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      
    - name: Configure kubectl
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
        
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployments/k8s/